export const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  SELECTED_CATEGORY: "SELECTED_CATEGORY",
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  ADDQTYTOCART: "ADDQTYTOCART",
  CLEAR_CART: "CLEAR_CART",
  SET_QUANTITY: "SET_QUANTITY",
};
